language: php
before_install:
- openssl aes-256-cbc -K $encrypted_79f4f9c97fc5_key -iv $encrypted_79f4f9c97fc5_iv -in configkube.enc -out configkube -d
- export KUBECONFIG="$(pwd)/configkube"
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- "./kubectl get pods"
php:
- 5.5
script: phpunit Test.php
